// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAPI(arg1) {
  return window['go']['main']['App']['CheckAPI'](arg1);
}

export function CheckMultiple(arg1) {
  return window['go']['main']['App']['CheckMultiple'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
